AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-springboot-sample
  Sample SAM Template for lambda-springboot

Globals:
  Function:
    Tracing: Active
    CodeUri: target/springboot-lambda-function-1.0.0-SNAPSHOT-aws.jar
#    Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    Handler: software.amazonaws.example.product.product.handler.MvcProductFunction::handleRequest
#    Runtime: java11
    Timeout: 45
    MemorySize: 1024
    Environment:
      Variables:
        JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
        PRODUCT_TABLE_NAME: !Ref ProductsTable

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Name: My Lambda springboot GraalVM Sample API

  ControllerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        GetRequestById:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for Springboot sample function"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/controller/"
